-- /home/xmren/gemini/X_download_article/output/DtDt666_张朝阳再次强调：年轻人千万不要负债！（讲透了社会底层被剥削的真实情景）_2026-01-27/DtDt666_张朝阳再次强调：年轻人千万不要负债！（讲透了社会底层被剥削的真实情景）_2026-01-27.sdr/metadata.epub.lua
return {
    ["annotations"] = {},
    ["cache_file_path"] = "/home/xmren/.config/koreader/cache/cr3cache/DtDt666_2026-01-27.epub.912d870b.1.cr3",
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 30,
    ["doc_path"] = "/home/xmren/gemini/X_download_article/output/DtDt666_张朝阳再次强调：年轻人千万不要负债！（讲透了社会底层被剥削的真实情景）_2026-01-27/DtDt666_张朝阳再次强调：年轻人千万不要负债！（讲透了社会底层被剥削的真实情景）_2026-01-27.epub",
    ["doc_props"] = {
        ["authors"] = "DtDt666",
        ["identifiers"] = "627dbb45-8ba5-4147-8261-532bbf1b83ff",
        ["language"] = "en",
        ["title"] = "张朝阳再次强调：年轻人千万不要负债！（讲透了社会底层被剥削的真实情景）",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[2]/body/div/div/article/div/div/div[3]/div[5]/div/div/div[5]/div/button/div/div/svg.0",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "f16e127caa9f8e2bba351bd2d4b4b686",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 1,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "DtDt666",
        ["highlights"] = 0,
        ["language"] = "en",
        ["notes"] = 0,
        ["pages"] = 30,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "张朝阳再次强调：年轻人千万不要负债！（讲透了社会底层被剥削的真实情景）",
    },
    ["summary"] = {
        ["modified"] = "2026-01-27",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
